mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

handler404 = 'polls.views.view_404'
urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('admin/', admin.site.urls),
                  path('polls/', include('polls.urls', namespace="polls")),
                  path('accounts/', include('users.urls', namespace="users")),
                  re_path(r'^oauth/', include('social_django.urls', namespace='social')),
                  path('password-reset-complete/',
                       auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                       name='password_reset_complete'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "polls"

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login')),
    path('create_new_form/<int:order_id>', views.create_new_form, name='create_new_form'),
    path('make_active_form/<int:form_id>', views.make_active_form, name='make_active_form'),
    path('form_creation/<int:id>/', views.form_creation, name='form_creation'),
    path('form_creation/<int:id>/save_config/', views.form_save_config, name='form_save_config'),
    path('form_creation/<int:id>/save_duration_rep_config/', views.form_save_duration_rep_config, name='form_save_duration_rep_config'),
    path('form_creation/<int:id>/get_configuration/', views.form_get_config, name='form_get_config'),
    path('download_form_data/<int:form_id>', views.download_form_data, name='download_form_data'),
    path('organization/<int:org_id>', views.orgranization, name='organization'),
    path('create_organization', views.create_organization, name='create_organization'),
    path('change_order_balance/<int:order_id>', views.change_order_balance, name='change_order_balance'),
    path('top_up_balance/<int:org_id>', views.top_up_balance, name='top_up_balance'),
    path('get_order_transactions/<int:order_id>', views.get_order_transactions, name='get_order_transactions'),
    path('order/<int:order_id>', views.order, name='order'),
    path('create_order/<int:org_id>', views.create_order, name='create_order'),
    path('change_order_status/<int:order_id>/<str:status>', views.change_order_status, name='change_order_status'),
    path('change_source_status/<str:source_name>', views.change_source_status, name='change_source_status'),
    path('get_filtered_orders/', views.get_filtered_orders, name='get_filtered_orders'),
    path('tasks', views.tasks, name='tasks'),
    path('get_order_instruction/<int:order_id>', views.get_order_instruction, name='get_order_instruction'),
    path('create_task/<int:order_id>', views.create_task, name='create_task'),
    path('task_implementation/<int:task_id>', views.task_implementation, name='task_implementation'),
    path('task_implementation/save_form_answer/<int:task_id>', views.save_form_answer, name='save_form_answer'),
    path('task_imlementation/complete_task/<int:task_id>', views.complete_task, name='complete_task'),
    path('change_profile_balance', views.change_profile_balance, name='change_profile_balance')
]

mysite/users/urls.py
from django.urls import path
from .views import home, profile, RegisterView
from django.contrib import admin

from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from .views import CustomLoginView, ResetPasswordView, ChangePasswordView

from .forms import LoginForm
from . import views

app_name = "urls"

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('', home, name='users-home'),
                  path('register/', RegisterView.as_view(), name='users-register'),
                  path('profile/', profile, name='users-profile'),

                  path('login/',
                       CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                               authentication_form=LoginForm), name='login'),

                  path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

                  path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

                  path('password-reset-confirm/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
                       name='password_reset_confirm'),

                  path('password-change/', ChangePasswordView.as_view(), name='password_change'),
                  path('get_nav_info/', views.get_nav_info, name='get_nav_info'),

                  re_path(r'^oauth/', include('social_django.urls', namespace='social')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=19, decimal_places=4, default=0)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

    class Meta:
        permissions = (
            ("can_implement_tasks", "To earn money$"),
            ("can_create_tasks", "To create tools"),
            ("can_use_business_interface", "To use creators tools"))

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Profile


class RegisterForm(UserCreationForm):
    # fields we want to include and customize in our form
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def clean_email(self):
        # Check that email is not duplicate
        username = self.cleaned_data["username"]
        email = self.cleaned_data["email"]
        users = User.objects.filter(email__iexact=email).exclude(username__iexact=username)
        if users:
            raise forms.ValidationError('Пользователь с таким e-mail уже существует.')
        return email.lower()

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

mysite/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.models import Permission, User
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
import json
from polls.models import Organization, Transaction

from .forms import RegisterForm, LoginForm, UpdateUserForm, UpdateProfileForm


def home(request):
    print(request.user)
    return render(request, 'users/home.html')


def get_nav_info(request):
    data = {}
    if request.user.is_anonymous:
        data['type'] = 'anonymous'
    elif Organization.objects.filter(profile=request.user.profile):
        org = Organization.objects.filter(profile=request.user.profile)
        data['type'] = 'organization'
        data['id'] = org[0].id
        data['name'] = request.user.username
        data['avatar'] = request.user.profile.avatar.url
    elif request.user.profile:
        data['type'] = 'profile'
        data['id'] = request.user.profile.id
        data['name'] = request.user.username
        data['avatar'] = request.user.profile.avatar.url
        data['balance'] = request.user.profile.balance
    return JsonResponse({'status': 'Valid request', "data": data}, status=200)


class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='users:/')

        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Аккаунт создан для {username}')

            return redirect(to='users:login')

        return render(request, self.template_name, {'form': form})


class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')
        if not remember_me:
            self.request.session.set_expiry(0)

            self.request.session.modified = True

        return super(CustomLoginView, self).form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "Мы отправили вам по электронной почте инструкции по установке вашего пароля, " \
                      "если существует учетная запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время." \
                      "Если вы не получите электронное письмо," \
        "пожалуйста, убедитесь, что вы ввели адрес, по которому регистрировались, и проверьте свою папку со спамом."
    success_url = reverse_lazy('users:login')


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Пароль успешно изменён"
    success_url = reverse_lazy('users:users-home')


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Ваш профиль успешно обновлён')
            return redirect(to='users:users-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
        profile = request.user.profile
        org = Organization.objects.filter(profile=profile)
        users_done_tasks = len(Transaction.objects.filter(status='DN').select_related('task').filter(
            task__executor_id=request.user.profile.id))
        users_undone_tasks = len(Transaction.objects.filter(status='CN').select_related('task').filter(
            task__executor_id=request.user.profile.id))
        users_earned_money = sum(Transaction.objects.filter(status='DN').select_related('task').filter(
            task__executor_id=request.user.profile.id).values_list('res_sum', flat=True))
        print(users_earned_money)
        # request.user.user_permissions.add(Permission.objects.get(codename="view_profile")) # тестирование добавления
        # print(request.user.get_user_permissions())
        # print(request.user.has_perm("users.view_profile"))
    return render(request, 'users/profile.html',
                  {'user_form': user_form, 'profile_form': profile_form, "profile": profile, 'org': len(org),
                   'users_done_tasks': users_done_tasks, 'users_undone_tasks': users_undone_tasks,
                   "users_earned_money": users_earned_money})

mysite/users/templates/users/base.html
<!doctype html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <title>{% block title %} {% endblock %} </title>
</head>
<body>
<div class="container p-3 my-3">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
                <a href="/" class="navbar-brand">Home</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <a href="{% url 'users:users-profile' %}" class="nav-item nav-link">Profile</a>
                            <a href="{% url 'users:logout' %}" class="nav-item nav-link">Logout</a>
                        {% else %}
                            <a href="{% url 'users:login' %}" class="nav-item nav-link">Sign in</a>
                        {% endif %}

                    </div>
                </div>
            </nav>
            <!--Any flash messages pop up in any page because this is the base template-->
            {% if messages %}
                <div class="alert alert-dismissible" role="alert">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<!-- A plugin for password show/hide  -->
<script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

</body>
</html>

mysite/users/templates/users/home.html
{% extends "src/base.html" %}
{% block title %} Домашняя страница {% endblock title%}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Добро пожаловать, {{user.first_name.title|default:'Guest'}}</h1>
        <p class="lead">
            Это <b>система регистраци пользоватял</b>
        </p>
        <hr class="my-4">
        <p class="lead">
            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg" href="{% url 'users:logout' %}" role="button">Выйти</a>
            {% else %}
                <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}" role="button">Войти</a>
            {% endif %}
        </p>
    </div>

{% endblock content %}

mysite/users/templates/users/login.html
{% extends "src/base.html" %}
{% load i18n %}
{% block title %} Вход {% endblock title %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <h3 class="font-weight-light my-1 text-center">Вход</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{% blocktranslate %}{{ value }}{% endblocktranslate %}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <a href="{% url 'social:begin' 'github' %}"
                                               class="btn btn-link btn-lg active btn-block">Войти с помощью GitHub</a>
                                            <a href="{% url 'social:begin' 'google-oauth2' %}"
                                               class="btn btn-link btn-lg active btn-block">Войти с помощью Google</a>
                                            <hr>
                                            <p class="text-center"><strong>ИЛИ</strong></p>
                                            <hr>
                                            <label class="small mb-1">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1">Пароль</label>
                                            {{ form.password }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <!-- Add a Remember me functionality -->
                                            {{ form.remember_me }}
                                            <label> Запомнить меня</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button name="login" class="col-md-12 btn btn-dark" id="login">Войти
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:users-register' %}">Ещё не зарегестрированы? Создать аккаунт</a><br>
                                <a href="{% url 'users:password_reset' %}"><i>Забыли пароль?</i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

mysite/users/templates/users/logout.html
{% extends "src/base.html" %}
{% block title %}Выход{% endblock title %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Вы успешно вышли из системы</h5>
        <p class="card-text">
            Спасибо за ваше время! Если есть пожелания или вопросы, обращайтесь по электронной почте :)
        </p>
        <br><hr><a href="{% url 'users:login' %}" class="btn btn-primary">Войти снова</a>
        </div>
    </div>


{% endblock content %}

mysite/users/templates/users/password_reset.html
{% extends "src/base.html" %}
{% block title %} Восстановление пароля {% endblock title %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                            <h3 class="font-weight-light my-4 text-center">Забыли пароль?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_email">Email</label>
                                            <input type="email" name="email" class="form-control"
                                                   autocomplete="email" maxlength="254" required id="id_email"
                                                   placeholder="Введите email">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark">Восстановить пароль
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:users-register' %}">Зарегестрироваться</a><br><br>
                                <a href="{% url 'users:login' %}">Вернуться на страницу входа</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

mysite/users/templates/users/password_reset_complete.html
{% extends "src/base.html" %}
{% block title %} Пароль установлен {% endblock title %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Ваш пароль установлен, вы можете продолжить и <a href="{% url 'users:login' %}">Войти в аккаунт</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

mysite/users/templates/users/password_reset_email.html
{% autoescape off %}
  Чтобы восстановить пароль для вашей учётной записи с email {{ user.email }} в Burlak,
  нажмите на сссылку ниже:

  {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

  Если ссылка не открывается по нажатию, пожалуйста, скопируйте её и вставьте в поисковую строку браузера.

  С большой любовью в сердце,
  Разработчик
{% endautoescape %}